package persistence.domain.mandat;
// Generated 9 dï¿½c. 2019 13:58:28 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import com.fasterxml.jackson.annotation.JsonBackReference;


/**
 * MandatMinuteHistorique generated by hbm2java
 */
@Entity
@Table(name = "Test_HISTORIQUE", schema = "SMILE")
public class TestHistorique implements java.io.Serializable {

	private BigDecimal numSeqHistoriqueMandat;
	private MandatMinute mandatMinute;
	private String codMandat;
	private String destination;
	private String terminalId;
	private String structure;
	private BigDecimal matricule;
	private String commentaire;
	private Date dateMiseAjour;
	private String numOperOmp;
	private Date dateTransaction;
	private Integer heureTransaction;
	private Long numeroTransaction;
	private String approvalCode;
	private String orderId;
	private String usernameCompteJointDegital;


	

	@Id
	@SequenceGenerator(name = "id_SequenceH", sequenceName = "MANDAT_MINUTE_HIST_SEQUENCE" ,initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_SequenceH")
	@Column(name = "NUM_SEQ_HISTORIQUE_MANDAT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumSeqHistoriqueMandat() {
		return this.numSeqHistoriqueMandat;
	}

	public void setNumSeqHistoriqueMandat(BigDecimal numSeqHistoriqueMandat) {
		this.numSeqHistoriqueMandat = numSeqHistoriqueMandat;
	}

	
	
	@Column(name = "HEURE_TRANSACTION", nullable = true)
	public Integer getHeureTransaction() {
		return heureTransaction;
	}

	public void setHeureTransaction(Integer heureTransaction) {
		this.heureTransaction = heureTransaction;
	}

	@Column(name = "DATE_TRANSACTION", nullable = true)
	public Date getDateTransaction() {
		return this.dateTransaction;
	}

	public void setDateTransaction(Date dateTransaction) {
		this.dateTransaction = dateTransaction;
	}
	@Column(name = "NUMERO_TRANSACTION", nullable = true)
	public Long getNumeroTransaction() {
		return this.numeroTransaction;
	}

	public void setNumeroTransaction(Long numeroTransaction) {
		this.numeroTransaction = numeroTransaction;
	}

	@Column(name = "DATE_MISE_A_JOUR", nullable = false, precision = 6, scale = 0)
	public Date getDateMiseAjour() {
		return dateMiseAjour;
	}

	public void setDateMiseAjour(Date dateMiseAjour) {
		this.dateMiseAjour = dateMiseAjour;
	}
	@Column(name = "COMMENTAIRE", nullable = false, precision = 6, scale = 0)
	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NUM_SEQ_MANDAT", nullable = false)
	@JsonBackReference
	@XmlTransient
	public MandatMinute getMandatMinute() {
		return this.mandatMinute;
	}

	
	
	
	public void setMandatMinute(MandatMinute mandatMinute) {
		this.mandatMinute = mandatMinute;
	}

	@Column(name = "COD_MANDAT", nullable = false)
	public String getCodMandat() {
		return this.codMandat;
	}

	public void setCodMandat(String codMandat) {
		this.codMandat = codMandat;
	}

	@Column(name = "DESTINATION", nullable = false, length = 5)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Column(name = "TERMINAL_ID", length = 20)
	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	@Column(name = "STRUCTURE", length = 20)
	public String getStructure() {
		return this.structure;
	}

	public void setStructure(String structure) {
		this.structure = structure;
	}

	@Column(name = "MATRICULE", precision = 22, scale = 0)
	public BigDecimal getMatricule() {
		return this.matricule;
	}

	public void setMatricule(BigDecimal matricule) {
		this.matricule = matricule;
	}
	
	@Column(name = "NUM_OPER_OMP", nullable = true, length = 255)
	public String getNumOperOmp() {
		return numOperOmp;
	}

	public void setNumOperOmp(String numOperOmp) {
		this.numOperOmp = numOperOmp;
	}

	@Column(name = "approval_code")
	public String getApprovalCode() {
		return approvalCode;
	}

	public void setApprovalCode(String approvalCode) {
		this.approvalCode = approvalCode;
	}

	@Column(name = "order_id")
	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "LOGIN_COMPTE_JOINT_DIGITAL")
	public String getUsernameCompteJointDegital() {
		return usernameCompteJointDegital;
	}

	public void setUsernameCompteJointDegital(String usernameCompteJointDegital) {
		this.usernameCompteJointDegital = usernameCompteJointDegital;
	}
	
	
	


	
	
	
	
}