package persistence.domain.mandat;
// Generated 9 dï¿½c. 2019 13:58:28 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import persistence.util.Constants;

/**
 * MandatMinute generated by hbm2java
 */
@Entity
@Table(name = "TEST", schema = "SMILE", uniqueConstraints = @UniqueConstraint(columnNames = "COD_MANDAT"))
public class Test implements java.io.Serializable {

	private BigDecimal numSeqMandat;
	private String codMandat; //automatically
	private Long montantMandat;
	//private String etatMandat;   minute 
	private Date dateCreation;
//	private String sourceCreationMandat; // SMILE, EBANKING, mBANKING
	// private String typeMoyPay;
	private String compte;  ///  banka  cpmpte courant epargne 
	private String cinEmeteur;
	//private String structureInit;
//	private Integer etatEnvSms;
	private Integer numTelEmetteur;
//	private Integer nbrTentative;
	private Date dateValidite;
	private String cinRecepteur;
	private String nomRecepteur;
	private String prenomRecepteur;
	//private String usernameCompteJointDegital;




	private Set<TestMinuteHistorique> testHistoriques = new HashSet<TestMinuteHistorique>(0);

	

	@Id
	@SequenceGenerator(name = "id_Sequence", sequenceName = Constants.MANDAT_MINUTE_SEQUENCE, initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_Sequence")
	@Column(name = "NUM_SEQ_MANDAT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumSeqMandat() {
		return this.numSeqMandat;
	}

	public void setNumSeqMandat(BigDecimal numSeqMandat) {
		this.numSeqMandat = numSeqMandat;
	}

	@Column(name = "COD_MANDAT", unique = true, nullable = false)
	public String getCodMandat() {
		return this.codMandat;
	}

	public void setCodMandat(String codMandat) {
		this.codMandat = codMandat;
	}

	// @Column(name = "MONTANT_MANDAT", nullable = false, precision = 22, scale = 0)
	// public BigDecimal getMontantMandat() {
	// return this.montantMandat;
	// }
	//
	// public void setMontantMandat(BigDecimal montantMandat) {
	// this.montantMandat = montantMandat;
	// }

	@Column(name = "ETAT_MANDAT", nullable = false, length = 1)
	public String getEtatMandat() {
		return this.etatMandat;
	}

	public void setEtatMandat(String etatMandat) {
		this.etatMandat = etatMandat;
	}

	@Column(name = "DATE_CREATION")
	@Type(type = "timestamp")
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "SOURCE_CREATION_MANDAT", nullable = false, length = 10)
	public String getSourceCreationMandat() {
		return this.sourceCreationMandat;
	}

	public void setSourceCreationMandat(String sourceCreationMandat) {
		this.sourceCreationMandat = sourceCreationMandat;
	}

	// @Column(name = "TYPE_MOYEN", nullable = false, length = 6)
	// public String getTypeMoyen() {
	// return this.typeMoyen;
	// }
	//
	// public void setTypeMoyen(String typeMoyen) {
	// this.typeMoyen = typeMoyen;
	// }
	//
	// @Column(name = "NUM_MOYEN", nullable = false, length = 16)
	// public String getNumMoyen() {
	// return this.numMoyen;
	// }
	//
	// public void setNumMoyen(String numMoyen) {
	// this.numMoyen = numMoyen;
	// }

	@Column(name = "TYPE_MOY_PAY", nullable = false, length = 10)
	public String getTypeMoyPay() {
		return typeMoyPay;
	}

	@Column(name = "MONTANT", nullable = false)
	public Long getMontantMandat() {
		return montantMandat;
	}

	public void setMontantMandat(Long montantMandat) {
		this.montantMandat = montantMandat;
	}

	public void setTypeMoyPay(String typeMoyPay) {
		this.typeMoyPay = typeMoyPay;
	}

	@Column(name = "NBR_TENTATIVE", nullable = true)
	public Integer getNbrTentative() {
		return nbrTentative;
	}

	public void setNbrTentative(Integer nbrTentative) {
		this.nbrTentative = nbrTentative;
	}

	@Column(name = "COMPTE", nullable = true)
	public String getCompte() {
		return compte;
	}

	public void setCompte(String compte) {
		this.compte = compte;
	}

	@Column(name = "CIN_EMETEUR", nullable = false, length = 8)
	public String getCinEmeteur() {
		return this.cinEmeteur;
	}

	public void setCinEmeteur(String cinEmeteur) {
		this.cinEmeteur = cinEmeteur;
	}

	@Column(name = "STRUCTURE_INIT", nullable = false, length = 3)
	public String getStructureInit() {
		return this.structureInit;
	}

	public void setStructureInit(String structureInit) {
		this.structureInit = structureInit;
	}

	@Column(name = "ETAT_ENV_SMS", nullable = false, precision = 1, scale = 0)
	public Integer getEtatEnvSms() {
		return this.etatEnvSms;
	}

	public void setEtatEnvSms(Integer etatEnvSms) {
		this.etatEnvSms = etatEnvSms;
	}

	@Column(name = "NUM_TEL_EMETTEUR", precision = 8, scale = 0)
	public Integer getNumTelEmetteur() {
		return this.numTelEmetteur;
	}

	public void setNumTelEmetteur(Integer numTelEmetteur) {
		this.numTelEmetteur = numTelEmetteur;
	}

	// @Column(name = "NBR_TENTATIVE", nullable = false, precision = 1, scale = 0)
	// public boolean isNbrTentative() {
	// return this.nbrTentative;
	// }
	//
	// public void setNbrTentative(boolean nbrTentative) {
	// this.nbrTentative = nbrTentative;
	// }

	@Column(name = "DATE_VALIDITE")
	@Type(type = "timestamp")
	public Date getDateValidite() {
		return this.dateValidite;
	}

	public void setDateValidite(Date dateValidite) {
		this.dateValidite = dateValidite;
	}

	@Column(name = "CIN_RECEPTEUR", nullable = false, length = 8)
	public String getCinRecepteur() {
		return this.cinRecepteur;
	}

	@Column(name = "NOM_RECEPTEUR", nullable = true, length = 20)
	public String getNomRecepteur() {
		return nomRecepteur;
	}

	public void setNomRecepteur(String nomRecepteur) {
		this.nomRecepteur = nomRecepteur;
	}

	@Column(name = "PRENOM_RECEPTEUR", nullable = true, length = 20)
	public String getPrenomRecepteur() {
		return prenomRecepteur;
	}

	public void setPrenomRecepteur(String prenomRecepteur) {
		this.prenomRecepteur = prenomRecepteur;
	}

	public void setCinRecepteur(String cinRecepteur) {
		this.cinRecepteur = cinRecepteur;
	}

	@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "mandatMinute")
	@JsonManagedReference
	public Set<MandatMinuteHistorique> getMandatMinuteHistoriques() {
		return this.mandatMinuteHistoriques;
	}

	public void setMandatMinuteHistoriques(Set<MandatMinuteHistorique> mandatMinuteHistoriques) {
		this.mandatMinuteHistoriques = mandatMinuteHistoriques;
	}

	@Column(name="LOGIN_COMPTE_JOINT_DIGITAL")
	public String getUsernameCompteJointDegital() {
		return usernameCompteJointDegital;
	}

	public void setUsernameCompteJointDegital(String usernameCompteJointDegital) {
		this.usernameCompteJointDegital = usernameCompteJointDegital;
	}
	
	


	
}
